modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/block-detective/issues"

[[mods]]
modId="block_detective"
version="1.1.0"
displayName="Block Detective"
itemIcon="minecraft:spyglass"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/BlockDetective.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/block-detective"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
This mod shows you the properties of all blocks!
'''

[[dependencies.block_detective]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.block_detective]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
