modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/block-detective/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:spyglass"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/BlockDetective.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/block-detective"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This mod shows you the properties of all blocks!'''


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

