modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/blockdetective/issues"

[[mods]]
modId="block_detective"
version="1.0.0"
displayName="Block Detective"
itemIcon="minecraft:spyglass"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/BlockDetective.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/blockdetective"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
This mod shows you the properties of all blocks!
'''

[[dependencies.upcycle]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.upcycle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
